import { AlertWrapper,
         AuthorCite,
         AuthorInfo,
         AuthorName,
         AuthorText,
         BooksUseTransitionContainer,
         ButtonGeneral,
         ButtonPostForm,
         ButtonUseTransition,
         ButtonWrapper,
         ButtonsOptContextStyle,
         ChildWrapper,
         CiteContainer,
         Container,
         ContainerPaginated,
         ContainerPostForm,
         CoverContainer,
         CustomTitleStyle,
         DisplayWrapper,
         Emoji,
         ErrorMessage,
         ErrorMessagePagination,
         Fieldset,
         Form,
         FormGroup,
         FormPost,
         FormWrapper,
         FormWrapperDeferred,
         HeavyComponentWrapper,
         Input,
         InputPost,
         KeyExerciseWrapper,
         Label,
         ListWrapper,
         LoadingMessage,
         LoadingMessagePagination,
         LoadingSpan,
         MainMealContainer,
         MasterWrapper,
         MealItem,
         MealLabel,
         MealListContainer,
         ModalBackground,
         ModalContent,
         MultipleFormWrapper,
         NextPageButton,
         OpenModalWrapper, OutQuotContainer, OutsideTable, PageButton, PageNumber, Panel,
         PrimaryButton,
         QuoteBlock,
         QuoteBlockPagination,
         QuoteText,
         QuoteTextPagination,
         QuotesContainer,
         QuotesContainerPagination,
         ReviewsContainer,
         SectionItemCenterWrapper,
         SectionWrapper,
         ShoppingCounterWrapper,
         SingleButtonWrapper,
         StepFlowWrapper, TableTitleWrapper, Title, TitleForQuote, TitlePaginated, TitlePostForm, ToolTipWrapper, WriterContainer } from "./styled.components";

/**react-design-patterns-app - version 28.00 - styledcomponents > index
 * - Features: 
 * 
 *     --> Importing and exporting 'LoadingSpan' 
 * 
 * Note: the macro 'tw' in order to work and use has to be installed
 * there is around 4 or 5 libraries and this is oen of the most active
 * and recent
 * 
 *          https://www.npmjs.com/package/twin.macro
 */

/**Sections and content */


export { SectionWrapper,
         CustomTitleStyle,
         Container,
         Panel, ListWrapper,
         ModalBackground,
         ModalContent,
         OpenModalWrapper,
         ButtonGeneral,
         FormWrapper,
         StepFlowWrapper,
         ButtonWrapper,
         AlertWrapper,
         MasterWrapper,
         ChildWrapper,
         PrimaryButton,
         KeyExerciseWrapper,
         FormWrapperDeferred,
         ButtonUseTransition,
         ReviewsContainer,
         CoverContainer,
         Emoji,
         WriterContainer,
         BooksUseTransitionContainer,
         ButtonsOptContextStyle,
         SingleButtonWrapper,
         HeavyComponentWrapper,
         DisplayWrapper,
         ToolTipWrapper,
         SectionItemCenterWrapper,
         OutsideTable,
         TableTitleWrapper,
         ShoppingCounterWrapper,
         MainMealContainer,
         MultipleFormWrapper,
         Form, Fieldset,
         ErrorMessage,
         TitleForQuote, QuotesContainer,
         LoadingMessage,
         OutQuotContainer,
         MealLabel, Input,
         QuoteBlock,
         QuoteText,
         AuthorCite,
         AuthorInfo,
         ContainerPostForm,
         AuthorName, Title,
         TitlePostForm,
         FormPost,
         Label,
         InputPost,
         ContainerPaginated,
         TitlePaginated, 
         ErrorMessagePagination,
         LoadingMessagePagination, 
         QuotesContainerPagination,
         QuoteBlockPagination,
         CiteContainer,
         AuthorText,
         PageButton,
         PageNumber,
         NextPageButton,
         LoadingSpan,
         QuoteTextPagination, ButtonPostForm, FormGroup, MealListContainer, MealItem }
